### ISSUE TITLE
Plugin gatsby-plugin-remove-generator is not compatible with your gatsby version 5.3.2 - It requires gatsby@2.x.x || 3.x.x || 4.x.x

### ISSUE THREAD

**Issue by danilobuerger** [tgallacher/gatsby-plugin-remove-generator#185]
When using this plugin I get the following warning message:

> Plugin gatsby-plugin-remove-generator is not compatible with your gatsby version 5.3.2 - It requires gatsby@2.x.x || 3.x.x || 4.x.x

**Comment by arsinclair** [comment]
Can someone add Gatsby v5 support?

There are PRs open since _Apr 1, 2022_, is this project dead?

**Comment by danilobuerger** [comment]
> Can someone add Gatsby v5 support?

It already works with Gatsby v5. This issue is just about getting the warning message removed.

**Comment by arsinclair** [comment]
It's not just warning, it actually breaks `npm install`. In order to work around this one needs to install using `npm install --legacy-peer-deps` or `npm install --force`, which is not ideal and can conceal other conflicts.

**Comment by arsinclair** [comment]
> This issue is just about getting the warning message removed

That's only partially true, a dependency tree needs to be updated as well. Currently it doesn't allow `gatsby@5` yet, therefore `npm install` fails. Of course using `--force` or `--legacy-peer-deps` arguments isn't desired and will require updating all our CI configurations.

This is what I get when trying to install _gatsby-plugin-remove-generator_:

> npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: payamha-iran.org-v2@1.0.0
npm ERR! Found: gatsby@5.6.0
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^5.6.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"2.x.x || 3.x.x || 4.x.x" from gatsby-plugin-remove-generator@1.2.0
npm ERR! node_modules/gatsby-plugin-remove-generator
npm ERR!   gatsby-plugin-remove-generator@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

I'm not so much worried about getting the warning off the way, but rather about updating the dependency tree.

**Comment by arsinclair** [comment]
> This issue is just about getting the warning message removed

That's only partially true, a dependency tree needs to be updated as well. Currently it doesn't allow `gatsby@5` yet, therefore `npm install` fails. Of course using `--force` or `--legacy-peer-deps` arguments isn't desired and will require updating all our CI configurations.

This is what I get when trying to install _gatsby-plugin-remove-generator_:

> npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: project-name@1.0.0
npm ERR! Found: gatsby@5.6.0
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^5.6.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"2.x.x || 3.x.x || 4.x.x" from gatsby-plugin-remove-generator@1.2.0
npm ERR! node_modules/gatsby-plugin-remove-generator
npm ERR!   gatsby-plugin-remove-generator@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

I'm not so much worried about getting the warning off the way, but rather about updating the dependency tree.

**Comment by arsinclair** [comment]
Can we have a word from the maintainer? @tgallacher what's your perspective on this? Would you be able to work on this? Would you like me to submit a PR?

**Comment by arsinclair** [comment]
Okay, I just tested my build without this plugin on Gatsby v5, and it looks like **Gatsby doesn't write it's version in the meta tags anymore**.

**Comment by tgallacher** [comment]
> Can we have a word from the maintainer? @tgallacher what's your perspective on this? Would you be able to work on this? Would you like me to submit a PR?

Happy for PRs!

This plugin isn't dead, I'm just not using GatsbyJS as much as I was. Will keep it alive though!

**Comment by arsinclair** [comment]
Great, here: https://github.com/tgallacher/gatsby-plugin-remove-generator/pull/192
